ARG DOCKER_REGISTRY_URL
ARG DINKY_VERSION=1.1.0-flink1.17
FROM ${DOCKER_REGISTRY_URL}dinkydocker/dinky-standalone-server:${DINKY_VERSION}

LABEL maintainer="zaizai <373045134@qq.com>"

ENV TZ=Asia/Shanghai
